# ******** Mend Unified CLI Template for Github ********
#
# You may wish to alter this file to override the build tool and Mend scanning technologies.
#
# For more configuration options, please check the technical documentation portal:
# 📚 https://docs.mend.io/bundle/integrations/page/scan_with_the_mend_cli.html
#
# ******** Description ********
# mend image will automatically scan an image for vulnerabilities with Operating System packages, Open Source vulnerabilities, and for secrets.
#
# If you are NOT using a service user and have multiple organizations, don't forget to set the organization using the scope parameter
# The following values should be added as environment variables with email and userkey being secrets
# MEND_URL: the mend url that you login to - (https://saas.mend.io) for example
# MEND_EMAIL: the user email for the mend platform account that you wish to scan with. This should be stored as a secret and then translated to MEND_EMAIL at runtime.
# MEND_USER_KEY: the user key found under my profile for the user you wish to scan with. This should be stored as a secret and then translated to MEND_USER_KEY at runtime.
# 
# REPO_NAME: The repository where the image should be stored/pulled from
# IMAGE_NAME: The name where the image should be stored/pulled from
# IMAGE_TAG: The tag for the image that you have built

name: Mend Image Scan

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE_NAME: IMAGE_NAME
  DOCKER_REPO_NAME: REPO_NAME
  DOCKER_TAG: dev-${{ github.run_number }}
  MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
  MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
  MEND_URL: https://saas.mend.io
  # MEND_URL: https://saas-eu.mend.io

  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Build the Docker image
      run: |
        docker buildx build --platform=linux/arm64 . --file Dockerfile --tag $DOCKER_REPO_NAME:$DOCKER_TAG --load
        docker images

    - name: Download Mend CLI & Run a Scan
      run: |
        curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
        mend image $DOCKER_REPO_NAME:$DOCKER_TAG --format sarif --filename results.sarif --local-pull
      
    - name: Upload sarif
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
