    container_name: wss-ghe-app
    environment:
      LOG_LEVEL: DEBUG
    ports:
      - "9494:9494"
      - "5678:5678"
    volumes:
      - "/home/ubuntu/agent-4-github-enterprise-25.8.1.2/wss-configuration/config/prop.json:/etc/usr/local/whitesource/conf/prop.json"
    depends_on: [remediate]
    logging:
      driver: local
      options: { max-size: 1m, max-file: "5" }

  scanner:
    image: wss-scanner:25.8.1.1
    container_name: wss-scanner-ghe
    environment:
      WS_UA_LOG_IN_CONSOLE: true
      LOG_LEVEL: DEBUG
      # For SBT global credentials and repos override
      SBT_USER: ${SBT_USER}
      SBT_PASS: ${SBT_PASS}
      SBT_REGISTRY_HOST: ${SBT_REGISTRY_HOST}
      SBT_BASE_URL: ${SBT_BASE_URL}
      SBT_RELEASES: ${SBT_RELEASES}
      SBT_SNAPSHOTS: ${SBT_SNAPSHOTS}
      SBT_PLUGIN_RELEASES: ${SBT_PLUGIN_RELEASES}
      # Force using ~/.sbt/repositories only
      SBT_OPTS: "-Dsbt.override.build.repos=true"
    ports:
      - "9393:9393"
    volumes:
      - "/home/ubuntu/agent-4-github-enterprise-25.8.1.2/wss-configuration/config/prop.json:/etc/usr/local/whitesource/conf/prop.json"
      - "/home/ubuntu/SBT/repositories:/home/wss-scanner/.sbt/repositories"
      - "/home/ubuntu/SBT/credentials.sbt:/home/wss-scanner/.sbt/1.0/credentials.sbt"
      - "/home/ubuntu/SBT/global.sbt:/home/wss-scanner/.sbt/1.0/global.sbt:ro"
    restart: always
    depends_on:
       - app
    # During setup, consider commenting these out until Artifactory proxies are confirmed:
    extra_hosts:
      - "repo.maven.apache.org:127.0.0.1"
      - "repo1.maven.org:127.0.0.1"
      - "repo2.maven.org:127.0.0.1"
      - "repo.scala-sbt.org:127.0.0.1"
      - "repo.typesafe.com:127.0.0.1"
    logging:
      driver: local
      options: { max-size: 1m, max-file: "5" }

networks:
  default:
    name: my_bridge
    external: false

                                                              
