services:
  remediate:
    image: wss-remediate:25.8.1
    container_name: remediate-server
    environment:
      LOG_LEVEL: DEBUG
      # For Renovate hostRules & packageRules
      SBT_USER: ${SBT_USER}
      SBT_PASS: ${SBT_PASS}
      SBT_REGISTRY_HOST: ${SBT_REGISTRY_HOST}
      SBT_BASE_URL: ${SBT_BASE_URL}
      SBT_RELEASES: ${SBT_RELEASES}
      SBT_SNAPSHOTS: ${SBT_SNAPSHOTS}
      SBT_PLUGIN_RELEASES: ${SBT_PLUGIN_RELEASES}
    ports:
      - "8080:8080"
    volumes:
      - "/home/ubuntu/agent-4-github-enterprise-25.8.1.2/wss-configuration/config/prop.json:/etc/usr/local/whitesource/conf/prop.json"
      - "/home/ubuntu/SBT/config.js:/usr/src/app/config.js"
    restart: always
    extra_hosts:
      # Optional: block default public registries
      - "repo.maven.apache.org:127.0.0.1"
      - "repo1.maven.org:127.0.0.1"
      - "repo2.maven.org:127.0.0.1"
      - "repo.scala-sbt.org:127.0.0.1"
      - "repo.typesafe.com:127.0.0.1"
    logging:
      driver: local
      options: { max-size: 1m, max-file: "5" }

  app:
    image: wss-ghe-app:25.8.1.2
    container_name: wss-ghe-app
    environment:
      LOG_LEVEL: DEBUG
    ports:
      - "9494:9494"
      - "5678:5678"
    volumes:
      - "/home/ubuntu/agent-4-github-enterprise-25.8.1.2/wss-configuration/config/prop.json:/etc/usr/local/whitesource/conf/prop.json"
    depends_on: [remediate]
    logging:
      driver: local
      options: { max-size: 1m, max-file: "5" }

  scanner:
    image: wss-scanner:25.8.1.1
    container_name: wss-scanner-ghe
    environment:
      WS_UA_LOG_IN_CONSOLE: true
      LOG_LEVEL: DEBUG
      # For SBT global credentials and repos override
      SBT_USER: ${SBT_USER}
      SBT_PASS: ${SBT_PASS}
