name: Mend CLI SCA Python Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv --user
        pip install -r requirements.txt
    
    - name: Mend CLI Scan
      env:
        MEND_EMAIL: ${{secrets.EMAIL}}
        MEND_USER_KEY: ${{secrets.USERKEY}}
        MEND_URL: https://saas-eu.whitesourcesoftware.com
      run: |
        echo Downloading Mend CLI
        curl https://downloads.mend.io/production/unified/latest/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
        mend sca -u
