name: Mend CLI NPM Maven Scan

on:
  push:
    branches: [ master* ]
  pull_request:
    branches: [ master* ]

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["12.x"]

    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install --only=prod
        
      - name: Mend CLI Scan
        env:
          MEND_EMAIL: ${{secrets.EMAIL}}
          MEND_USER_KEY: ${{secrets.USERKEY}}
          MEND_URL: https://saas-eu.whitesourcesoftware.com
        run: |
          echo Downloading Mend CLI
          curl https://downloads.mend.io/production/unified/latest/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
          mend sca -u
