---
trigger:
  - release*
pool:
  vmImage: ubunutu-latest

steps:
# Add your package manager build here
# Maven
  - task: Maven@3
    inputs:
      mavenPomFile: pom.xml
      goals: clean install
      mavenOptions: -DskipTests=true
      publishJUnitResults: false
      javaHomeOption: JDKVersion
      jdkVersionOption: "1.11"
      mavenVersionOption: Default
      mavenAuthenticateFeed: false
      effectivePomSkip: false
# NPM
  - task: NodeTool@0
    inputs:
        versionSpec: '12.x'
    displayName: 'Install Node.js'
  - task: Npm@1
    displayName: 'NPM Install'
    inputs:
        customCommand: install --package-lock

  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        echo "Downloading Mend CLI"
        curl https://downloads.mend.io/production/unified/latest/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
        echo "Start Mend SCA Scan"
        mend sca -u
        echo "Start Mend SAST Scan"
        mend sast
    env:
      #SCA
      MEND_EMAIL: $(MEND_SCA_EMAIL)
      MEND_USER_KEY: $(MEND_SCA_USERKEY)
      MEND_URL: https://saas.mend.io
      #SAST
      MEND_SAST_SERVER_URL: https://saas.mend.io/sast
      MEND_SAST_API_TOKEN: $(MEND_SAST_API)
      MEND_SAST_ORGANIZATION: $(MEND_SAST_ORGANIZATION)
    displayName: Mend CLI Scan
