# ******** Mend Unified CLI Template for Github Actions ********
#
# You may wish to alter this file to override the build tool and Mend scanning technologies.
#
# For more configuration options, please check the technical documentation portal:
# 📚 https://docs.mend.io/bundle/integrations/page/scan_with_the_mend_cli.html
#
# ******** Description ********
# mend dep will automatically use package managers and file system scanning to detect open source components.
# mend code will automatically detect languages and frameworks used in your projects to scan for code weaknesses.

# If you are NOT using a service user, and have multiple organizations, don't forget to call the scope -s parameter to set the organizatio

name: Mend

on:
  push:
    branches: [ main ]


jobs:

  call-template:
    # Replace the below with your own location
    uses: mend-examples/mend-toolkit/.github/workflows/mend-scan-template.yaml@scan-templates
    with:
      MEND_URL: "https://saas-eu.mend.io"
      # MEND_URL: "https://saas.mend.io"
      SCA: true
      SAST: false
      CN: false # TODO define template
      SCA_Reports: 'ALL' # Comma-separated list containing any of: SBOM,RISK,INVENTORY,DUE_DILIGENCE,ALL
    secrets:
      MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
      MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
      