# ******** Mend Unified CLI Template for Github Actions ********
#
# You may wish to alter this file to override the build tool and the Mend scanning technologies used (SCA, SAST or Conatiner).
#
# For more configeration options, please check the technical documentation portal:
# 📚 https://docs.mend.io/bundle/cli/page/scan_with_mend_s_unified_cli.html 
#
# ******** Description ********
# Mend SCA will automatically use package managers and file system scanning to detect open source components. 
# Mend SAST will automatically detect languages and frameworks used in your projects to scan for code weaknesses.
# Mend Containers will automatically pull the container defined and scan for open source components. 

name: Mend CLI Scan

on:
  push:
    branches: [ master ]

jobs:
  build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        ## Add your package manager build here
        - uses: actions/setup-dotnet@v1
        - uses: actions/setup-java@v2
        - uses: actions/setup-node@v3
        
        - name: Mend CLI Scan
          env:
            #SCA
            MEND_EMAIL: ${{secrets.MEND_SCA_EMAIL}}
            MEND_USER_KEY: ${{secrets.MEND_SCA_USERKEY}}
            MEND_URL: https://saas.mend.io
            #SAST
            MEND_SAST_SERVER_URL: https://saas.mend.io/sast
            MEND_SAST_API_TOKEN: ${{secrets.MEND_SAST_API}}
            MEND_SAST_ORGANIZATION: ${{secrets.MEND_SAST_ORGANIZATION}}
          run: |
            echo Downloading Mend CLI
            curl -LJO https://downloads.mend.io/production/unified/latest/linux_amd64/mend && chmod +x mend
            echo Start Mend CLI scan
            ./mend sca -u
            ./mend sast
