# ******** Mend Unified CLI Template for Gitlab CI ********
#
# You may wish to alter this file to override the build tool and the Mend scanning technologies used (SCA, SAST or Conatiner).
#
# For more configeration options, please check the technical documentation portal:
# 📚 https://docs.mend.io/bundle/cli/page/scan_with_mend_s_unified_cli.html 
#
# ******** Description ********
# Mend SCA will automatically use package managers and file system scanning to detect open source components. 
# Mend SAST will automatically detect languages and frameworks used in your projects to scan for code weaknesses.


default:
  image: maven:3.8-openjdk-11

stages:
  - build
  - scan

## Maven example - replace with your builds steps
maven_build:
  image: maven:3.8.4-eclipse-temurin-17-alpine
  stage: build
  script: "mvn clean install -DskipTests"
  
cache:
  key: "cache-$MVN_PKG-$CI_PIPELINE_ID"
  paths:
  - ${CI_PROJECT_DIR}/
## end maven build example

# The Mend SCA CLI scan should be called AFTER a package manager build step such as "mvn clean install -DskipTests=true" or "npm install --only=prod"

mend_cli_scan:
  stage: scan
  variables:
    ### SCA Environment Variables ###
    MEND_EMAIL: $MEND_SCA_EMAIL
    MEND_USER_KEY: $MEND_SCA_USERKEY
    MEND_URL: "https://saas.mend.io"
    ### SAST Environment Variables ###
    MEND_SAST_SERVER_URL: "https://saas.mend.io/sast"
    MEND_SAST_API_TOKEN: $MEND_SAST_API
    MEND_SAST_ORGANIZATION: $MEND_SAST_ORGANIZATION

  script: |

    echo Downloading Mend CLI
    curl -LJO https://downloads.mend.io/production/unified/latest/linux_amd64/mend && chmod +x mend
    echo Start Mend SCA Scan
    ./mend sca -u
    echo Start Mend SAST Scan
    ./mend sast